# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title:               ''
tagline:             ''
description:         ''
url:                 https://swapnai.github.io/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              
  url:               https://swapnai.github.io/
  email:             

# Custom vars
version:             1.0.0
gem: [jekyll-paginate, jekyll-gists]

# External gems
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag

exclude:
  - "/vendor/"

